name: Github Actions Demo
run-name: ${{ github.actor }} is testing out Github Actions ğŸš€

on: [push]

jobs:
  # This workflow contains a single job called "  Explore-Github-Actions"
  Explore-Github-Actions:

    # The type of runner that the job will run on
    runs-on: label-jarbelix

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Send greeting
        run: echo "Hello ${{ inputs.name }}"

      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."

      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by Github!"

      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - run: echo "The repository name is $GITHUB_REPOSITORY"
      
      - run: echo "variables $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"

      - name: condition
        if: runner.os != 'Windows'
        run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS."

      - name: Check out repository code
        uses: actions/checkout@v4
      
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      
      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}
      
      - run: echo "ğŸ This job's status is ${{ job.status }}."
